plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.1'
	id 'io.spring.dependency-management' version '1.1.5'
}

group = 'umc.kkijuk'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

test {
	systemProperty 'spring.profiles.active', 'test_local, test'
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'


	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'mysql:mysql-connector-java:8.0.32'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.openapitools:jackson-databind-nullable:0.2.1'

	implementation 'org.springframework.security:spring-security-crypto'
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'

	//s3
	implementation 'software.amazon.awssdk:s3:2.17.285'

	// OAuth2
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

	// Spring-security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	testImplementation 'org.springframework.security:spring-security-test'

	// Jwt
	implementation group:'io.jsonwebtoken', name: 'jjwt-api', version: '0.11.5'
	implementation group:'io.jsonwebtoken', name: 'jjwt-impl', version: '0.11.5'
	implementation group:'io.jsonwebtoken', name: 'jjwt-jackson', version: '0.11.5'

	// grafana
	implementation "org.springframework.boot:spring-boot-starter-actuator"
	runtimeOnly "io.micrometer:micrometer-registry-prometheus"

	// aop
	implementation 'org.springframework.boot:spring-boot-starter-aop'

}

tasks.named('test') {
	useJUnitPlatform()
}
