version: '3.8'

services:
 ## monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: kkijuk-prometheus
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus-config.yaml'
    ports:
      - "9090:9090"
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    container_name: kkijuk-grafana
#    set in instance
#    environment:
#      - GF_SECURITY_ADMIN_USER=local
#      - GF_SECURITY_ADMIN_PASSWORD=local
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - ./dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge

volumes:
  loki_data: