package umc.kkijuk.server.unitTest.mock;

import umc.kkijuk.server.career.domain.Employment;
import umc.kkijuk.server.career.repository.EmploymentRepository;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeEmploymentRepository implements EmploymentRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(1);
    private final List<Employment> data = new ArrayList<>();

    @Override
    public List<Employment> findByMemberId(Long memberId) {
        return data.stream()
                .filter(item -> Objects.equals(item.getMemberId(),memberId)).toList();
    }

    @Override
    public Optional<Employment> findById(Long employmentId) {
        return data.stream()
                .filter(item -> Objects.equals(item.getId(), employmentId)).toList().stream().findAny();
    }

    @Override
    public List<Employment> findByMemberIdAndNameContaining(Long memberId, String keyword) {
        return data.stream()
                .filter(item -> Objects.equals(item.getMemberId(), memberId)&&
                        item.getName() !=null &&
                        item.getName().contains(keyword)).toList();

    }

    @Override
    public Employment save(Employment emp) {
        if (emp.getId() == null || emp.getId() == 0) {
            Employment newEmp = Employment.builder()
                    .memberId(emp.getMemberId())
                    .name(emp.getName())
                    .alias(emp.getAlias())
                    .unknown(emp.getUnknown())
                    .startdate(emp.getStartdate())
                    .enddate(emp.getEnddate())
                    .type(emp.getType())
                    .position(emp.getPosition())
                    .field(emp.getField())
                    .build();

            setEndDate(newEmp);
            assignId(newEmp, autoGeneratedId.getAndIncrement());
            data.add(newEmp);
            return newEmp;
        }else{
            data.removeIf(e -> e.getId().equals(emp.getId()));
            data.add(emp);
            return emp;
        }
    }

    @Override
    public void delete(Employment employment) {
        data.removeIf(item -> Objects.equals(item.getId(), employment.getId()));
    }
    public List<Employment> findAll() {
        return new ArrayList<>(data);
    }
    private void assignId(Employment emp, Long id) {
        try {
            var field = Employment.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(emp, id);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("id 할당 실패 : ", e);
        }
    }
    private void setEndDate(Employment etc){
        if (etc.getUnknown()) {
            etc.setEnddate(LocalDate.now());
            etc.setYear(LocalDate.now().getYear());
        } else {
            etc.setYear(etc.getEnddate().getYear());
        }

    }
}
