package umc.kkijuk.server.unitTest.mock;

import umc.kkijuk.server.career.domain.EduCareer;
import umc.kkijuk.server.career.repository.EduCareerRepository;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeEduCareerRepository implements EduCareerRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(1);
    private final List<EduCareer> data = new ArrayList<>();
    @Override
    public List<EduCareer> findByMemberId(Long memberId) {
        return data.stream()
                .filter(item -> Objects.equals(item.getMemberId(), memberId)).toList();
    }

    @Override
    public List<EduCareer> findByMemberIdAndNameContaining(Long memberId, String keyword) {
        return data.stream()
                .filter(item -> Objects.equals(item.getMemberId(), memberId)&&
                        item.getName() !=null &&
                        item.getName().contains(keyword)).toList();

    }

    @Override
    public EduCareer save(EduCareer edu) {
        if (edu.getId() == null || edu.getId() == 0) {
            EduCareer newEduCareer = EduCareer.builder()
                    .memberId(edu.getMemberId())
                    .name(edu.getName())
                    .alias(edu.getAlias())
                    .unknown(edu.getUnknown())
                    .startdate(edu.getStartdate())
                    .enddate(edu.getEnddate())
                    .organizer(edu.getOrganizer())
                    .time(edu.getTime())
                    .build();

            setEndDate(newEduCareer);
            assignId(newEduCareer, autoGeneratedId.getAndIncrement());
            data.add(newEduCareer);
            return newEduCareer;

        } else {
            data.removeIf(a -> a.getId().equals(edu.getId()));
            data.add(edu);
            return edu;
        }
    }

    @Override
    public Optional<EduCareer> findById(Long educareerId) {
        return data.stream()
                .filter(item -> Objects.equals(item.getId(), educareerId)).findAny();

    }

    @Override
    public void delete(EduCareer eduCareer) {
        data.removeIf(item -> Objects.equals(item.getId(), eduCareer.getId()));
    }
    public List<EduCareer> findAll() {
        return new ArrayList<>(data);
    }
    private void assignId(EduCareer eduCareer, Long id) {
        try {
            var field = EduCareer.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(eduCareer, id);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("id 할당 실패 : ", e);
        }
    }
    private void setEndDate(EduCareer eduCareer){
        if (eduCareer.getUnknown()) {
            eduCareer.setEnddate(LocalDate.now());
            eduCareer.setYear(LocalDate.now().getYear());
        } else {
            eduCareer.setYear(eduCareer.getEnddate().getYear());
        }

    }
}
