package umc.kkijuk.server.unitTest.mock;

import umc.kkijuk.server.career.domain.Circle;
import umc.kkijuk.server.career.repository.CircleRepository;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeCircleRepository implements CircleRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(1);
    private final List<Circle> data = new ArrayList<>();

    @Override
    public Optional<Circle> findById(Long circleId) {
        return data.stream()
                .filter(item -> Objects.equals(item.getId(), circleId))
                .findAny();
    }

    @Override
    public List<Circle> findByMemberId(Long memberId) {
        return data.stream()
                .filter(item -> Objects.equals(item.getMemberId(), memberId))
                .toList();
    }

    @Override
    public List<Circle> findByMemberIdAndNameContaining(Long memberId, String keyword) {
        return data.stream()
                .filter(item -> Objects.equals(item.getMemberId(), memberId) &&
                        item.getName() != null &&
                        item.getName().contains(keyword)).toList();
    }

    public Circle save(Circle circle) {
        if (circle.getId() == null || circle.getId() == 0) {
            Circle newCircle = Circle.builder()
                    .memberId(circle.getMemberId())
                    .name(circle.getName())
                    .alias(circle.getAlias())
                    .unknown(circle.getUnknown())
                    .startdate(circle.getStartdate())
                    .enddate(circle.getEnddate())
                    .location(circle.getLocation())
                    .role(circle.getRole())
                    .build();

            setEndDate(newCircle);
            assignId(newCircle, autoGeneratedId.getAndIncrement());
            data.add(newCircle);
            return newCircle;
        } else {
            data.removeIf(a -> a.getId().equals(circle.getId()));
            data.add(circle);
            return circle;
        }
    }

    @Override
    public void delete(Circle circle) {
        data.removeIf(item -> Objects.equals(item.getId(), circle.getId()));
    }
    private void assignId(Circle circle, Long id) {
        try {
            var field = Circle.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(circle, id);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("id 할당 실패 : ", e);
        }
    }
    public List<Circle> findAll() {
        return new ArrayList<>(data);
    }
    public void clear() {
        data.clear();
        autoGeneratedId.set(0);
    }
    private void setEndDate(Circle circle){
        if (circle.getUnknown()) {
            circle.setEnddate(LocalDate.now());
            circle.setYear(LocalDate.now().getYear());
        } else {
            circle.setYear(circle.getEnddate().getYear());
        }

    }
}
