package umc.kkijuk.server.unitTest.mock;

import umc.kkijuk.server.career.domain.CareerEtc;
import umc.kkijuk.server.career.repository.CareerEtcRepository;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeCareerEtcRepository implements CareerEtcRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(1);
    private final List<CareerEtc> data = new ArrayList<>();


    @Override
    public List<CareerEtc> findByMemberId(Long memberId) {
        return data.stream()
                .filter(item -> Objects.equals(item.getMemberId(),memberId))
                .toList();
    }
    @Override
    public Optional<CareerEtc> findById(Long etcId) {
        return data.stream()
                .filter(item -> Objects.equals(item.getId(),etcId))
                .findAny();
    }

    @Override
    public List<CareerEtc> findByMemberIdAndNameContaining(Long memberId, String keyword) {
        return data.stream()
                .filter(item -> Objects.equals(item.getMemberId(), memberId)&&
                        item.getName() !=null &&
                        item.getName().contains(keyword)).toList();
    }

    @Override
    public CareerEtc save(CareerEtc etc) {
        if (etc.getId() == null || etc.getId() == 0) {
            CareerEtc newEtc = CareerEtc.builder()
                    .memberId(etc.getMemberId())
                    .name(etc.getName())
                    .alias(etc.getAlias())
                    .unknown(etc.getUnknown())
                    .startdate(etc.getStartdate())
                    .enddate(etc.getEnddate())
                    .build();

            setEndDate(newEtc);
            assignId(newEtc, autoGeneratedId.getAndIncrement());
            data.add(newEtc);
            return newEtc;
        }else{
            data.removeIf(e -> e.getId().equals(etc.getId()));
            data.add(etc);
            return etc;
        }
    }
    @Override
    public void delete(CareerEtc etc) {
        data.removeIf(item -> Objects.equals(item.getId(), etc.getId()));
    }
    public List<CareerEtc> findAll() {
        return new ArrayList<>(data);
    }
    private void assignId(CareerEtc etc, Long id) {
        try {
            var field = CareerEtc.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(etc, id);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("id 할당 실패 : ", e);
        }
    }
    private void setEndDate(CareerEtc etc){
        if (etc.getUnknown()) {
            etc.setEnddate(LocalDate.now());
            etc.setYear(LocalDate.now().getYear());
        } else {
            etc.setYear(etc.getEnddate().getYear());
        }

    }
}
