package umc.kkijuk.server.unitTest.mock;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;
import umc.kkijuk.server.career.domain.Competition;
import umc.kkijuk.server.career.repository.CompetitionRepository;

import java.util.List;
import java.util.Optional;

public class FakeCompetitionRepository implements CompetitionRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(1);
    private final List<Competition> data = new ArrayList<>();
    @Override
    public List<Competition> findByMemberId(Long memberId) {
        return data.stream()
            .filter(item -> Objects.equals(item.getMemberId(), memberId)).toList();

    }

    @Override
    public List<Competition> findByMemberIdAndNameContaining(Long memberId, String keyword) {
        return data.stream()
            .filter(item -> Objects.equals(item.getMemberId(), memberId)&&
                item.getName() !=null &&
                item.getName().contains(keyword)).toList();

    }

    @Override
    public Competition save(Competition competition) {
        if (competition.getId() == null || competition.getId() == 0) {
            Competition newCompetition = Competition.builder()
                .memberId(competition.getMemberId())
                .name(competition.getName())
                .alias(competition.getAlias())
                .unknown(competition.getUnknown())
                .startdate(competition.getStartdate())
                .enddate(competition.getEnddate())
                .organizer(competition.getOrganizer())
                .teamSize(competition.getTeamSize())
                .contribution(competition.getContribution())
                .isTeam(competition.getIsTeam())
                .build();

            setEndDate(newCompetition);
            assignId(newCompetition, autoGeneratedId.getAndIncrement());
            data.add(newCompetition);
            return newCompetition;

        } else {
            data.removeIf(a -> a.getId().equals(competition.getId()));
            data.add(competition);
            return competition;
        }
    }

    @Override
    public Optional<Competition> findById(Long competitionId) {
        return data.stream()
            .filter(item -> Objects.equals(item.getId(), competitionId)).findAny();

    }

    @Override
    public void delete(Competition comp) {
        data.removeIf(item -> Objects.equals(item.getId(), comp.getId()));
    }
    public List<Competition> findAll() {
        return new ArrayList<>(data);
    }
    private void assignId(Competition competition, Long id) {
        try {
            var field = Competition.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(competition, id);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("id 할당 실패 : ", e);
        }
    }
    private void setEndDate(Competition competition){
        if (competition.getUnknown()) {
            competition.setEnddate(LocalDate.now());
            competition.setYear(LocalDate.now().getYear());
        } else {
            competition.setYear(competition.getEnddate().getYear());
        }

    }
}
