package umc.kkijuk.server.unitTest.mock;

import umc.kkijuk.server.career.domain.Project;
import umc.kkijuk.server.career.repository.ProjectRepository;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeProjectRepository implements ProjectRepository{
    private final AtomicLong autoGeneratedId = new AtomicLong(1);
    private final List<Project> data = new ArrayList<>();


    @Override
    public List<Project> findByMemberId(Long memberId) {
        return data.stream()
                .filter(item -> Objects.equals(item.getMemberId(),memberId))
                .toList();
    }
    @Override
    public Optional<Project> findById(Long projectId) {
        return data.stream()
                .filter(item -> Objects.equals(item.getId(),projectId))
                .findAny();
    }

    @Override
    public List<Project> findByMemberIdAndNameContaining(Long memberId, String keyword) {
        return data.stream()
                .filter(item -> Objects.equals(item.getMemberId(), memberId)&&
                        item.getName() !=null &&
                        item.getName().contains(keyword)).toList();
    }

    @Override
    public Project save(Project project) {
        if (project.getId() == null || project.getId() == 0) {
            Project newProject = Project.builder()
                    .memberId(project.getMemberId())
                    .name(project.getName())
                    .alias(project.getAlias())
                    .unknown(project.getUnknown())
                    .startdate(project.getStartdate())
                    .enddate(project.getEnddate())
                    .isTeam(project.getIsTeam())
                    .teamSize(project.getTeamSize())
                    .contribution(project.getContribution())
                    .location(project.getLocation())
                    .build();

            setEndDate(newProject);
            assignId(newProject, autoGeneratedId.getAndIncrement());
            data.add(newProject);
            return newProject;
        }else{
            data.removeIf(p -> p.getId().equals(project.getId()));
            data.add(project);
            return project;
        }
    }
    @Override
    public void delete(Project project) {
        data.removeIf(item -> Objects.equals(item.getId(), project.getId()));
    }
    public List<Project> findAll() {
        return new ArrayList<>(data);
    }
    private void assignId(Project project, Long id) {
        try {
            var field = Project.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(project, id);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("id 할당 실패 : ", e);
        }
    }
    private void setEndDate(Project project){
        if (project.getUnknown()) {
            project.setEnddate(LocalDate.now());
            project.setYear(LocalDate.now().getYear());
        } else {
            project.setYear(project.getEnddate().getYear());
        }

    }
}
